services:
  db:
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/postgres_data:/var/lib/postgresql/data


  app:
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped