services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: softwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d softwork" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring-app
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: