# =====================================
#  ENVIRONMENT: PRODUCTION
# =====================================

# Database Connection
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Swagger Configuration URL
swagger.server.url=http://${API_HOST}:${PORT:8080}

# JPA / Hibernate
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=${PORT:8080}

# Security
authorization.jwt.secret=${JWT_SECRET}