# =====================================
#  ENVIRONMENT: DEVELOPMENT
# =====================================

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/softwork
spring.datasource.username=postgres
spring.datasource.password=postgres

# Swagger Configuration URL
swagger.server.url=http://localhost:8092

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inject Initial Data for tests
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Server Port
server.port=8092

# Security
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
