# =====================================
#  ENVIRONMENT: PRODUCTION
# =====================================

# Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/softwork}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# Swagger Configuration URL
swagger.server.url=https://${API_HOST}

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Initial Data
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=true

# Server Port
server.port=${PORT:8080}

# Security
authorization.jwt.secret=${JWT_SECRET}
authorization.jwt.expiration.days=${JWT_EXPIRATION_DAYS:7}
authorization.google.client-id=${GOOGLE_CLIENT_ID}

# External services
CLOUDINARY_URL=${CLOUDINARY_URL:***}
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
stripe.secret-key=${STRIPE_SECRET_KEY:***}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:***}
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY:***}
spring.ai.google.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.temperature=0.4