# =====================================
# INITIAL ENVIRONMENT
# =====================================

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql

spring.jpa.open-in-view=true

spring.jpa.hibernate.naming.physical-strategy=pe.edu.upc.soft.work.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

spring.jackson.property-naming-strategy=SNAKE_CASE
authorization.jwt.expiration.days=7
