package pe.edu.upc.soft.work.platform.worker.forum.interfaces.rest.resources;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

/**
 * Response payload containing the Employee Assistant's answer.
 *
 * @param contentAnswer the text generated by the AI
 */
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public record AssistantAnswerResponse(String contentAnswer) {
}
