package pe.edu.upc.soft.work.platform.worker.forum.application.internal.outboundservices.acl;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import pe.edu.upc.soft.work.platform.worker.forum.domain.model.commands.AskEmployeeAssistantCommand;
import pe.edu.upc.soft.work.platform.worker.forum.domain.model.valueObjects.AssistantAnswer;
import pe.edu.upc.soft.work.platform.worker.forum.domain.services.EmployeeAssistantService;

/**
 * Service that answers employee questions/concerns about the company using AI (Gemini).
 * Optionally enriches the prompt with basic company context obtained from the
 * Dashboard Bounded Context through the Worker Forum's own ACL outbound service.
 */
@Service
public class EmployeeAssistantServiceImpl implements EmployeeAssistantService {

  /**
   * AI chat client tailored with an employee-facing HR assistant persona.
   */
  private final ChatClient chatClient;

  /**
   * Outbound service used to fetch basic company context from the Dashboard context.
   */
  private final ExternalDashboardServiceFromWorkerForum externalDashboardService;

  /**
   * Constructor for EmployeeAssistantServiceImpl.
   *
   * @param chatClient               the AI chat client instance (employee assistant persona)
   * @param externalDashboardService the Dashboard ACL outbound service
   */
  public EmployeeAssistantServiceImpl(
      @Qualifier("employeeAssistantChatClient") ChatClient chatClient,
      ExternalDashboardServiceFromWorkerForum externalDashboardService) {
    this.chatClient = chatClient;
    this.externalDashboardService = externalDashboardService;
  }

  /**
   * Handles the request to the employee assistant.
   * Integrates company context if available and returns the assistant's generated response.
   *
   * @param command the command containing the employee's prompt and optional company ID
   * @return an AssistantAnswer containing the response generated by the AI
   * @throws RuntimeException if an error occurs during AI response generation
   */
  @Override
  public AssistantAnswer handle(AskEmployeeAssistantCommand command) {
    var contextBuilder = new StringBuilder();
    if (command.companyId() != null) {
      externalDashboardService.getCompanyNameById(command.companyId())
          .ifPresent(name -> contextBuilder
              .append("El empleado pertenece a la empresa: ").append(name).append(". "));
    }

    try {
      var response = chatClient.prompt()
          .user(u -> u.text(contextBuilder + command.prompt()))
          .call()
          .content();
      return new AssistantAnswer(response);
    } catch (Exception e) {
      throw new RuntimeException("Error generating assistant response: " + e.getMessage(), e);
    }
  }
}
