package pe.edu.upc.soft.work.platform.feedback.application.internal.outboundservices.acl;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;
import pe.edu.upc.soft.work.platform.feedback.domain.model.commands.AskFeedbackAssistantCommand;
import pe.edu.upc.soft.work.platform.feedback.domain.model.queries.GetSurveyByIdQuery;
import pe.edu.upc.soft.work.platform.feedback.domain.model.valueObjects.AssistantAnswer;
import pe.edu.upc.soft.work.platform.feedback.domain.services.FeedbackAssistantService;
import pe.edu.upc.soft.work.platform.feedback.domain.services.SurveyQueryService;

/**
 * Service to manage the feedback assistant interactions.
 * Uses AI to process feedback requests and provides contextual
 * information from surveys to enhance the assistant's responses.
 */
@Service
public class FeedbackAssistantServiceImpl implements FeedbackAssistantService {

  /**
   * AI chat client for generating assistant responses.
   */
  private final ChatClient chatClient;

  /**
   * Service to query survey information.
   */
  private final SurveyQueryService surveyQueryService;

  /**
   * Constructor for FeedbackAssistantServiceImpl.
   * @param chatClient         the AI chat client instance
   * @param surveyQueryService the survey query service instance
   */
  public FeedbackAssistantServiceImpl(ChatClient chatClient, SurveyQueryService surveyQueryService) {
    this.chatClient = chatClient;
    this.surveyQueryService = surveyQueryService;
  }

  /**
   * Handles the request to the feedback assistant.
   * Integrates survey context if available and returns the assistant's generated response.
   *
   * @param command the command containing the user prompt and optional survey ID
   * @return an AssistantAnswer containing the response generated by the AI
   * @throws RuntimeException if an error occurs during AI response generation
   */
  @Override
  public AssistantAnswer handle(AskFeedbackAssistantCommand command) {
    var contextBuilder = new StringBuilder();
    if (command.surveyId() != null){
      surveyQueryService.handle(new GetSurveyByIdQuery(command.surveyId()))
          .ifPresent(survey -> contextBuilder
              .append("Encuesta: ").append(survey.getTitle())
              .append(" - ").append(survey.getDescription()).append(". "));
    }

    try{
      var response = chatClient.prompt()
          .user(u -> u.text(contextBuilder + command.prompt()))
          .call()
          .content();
      return new AssistantAnswer(response);
    } catch (Exception e) {
      throw new RuntimeException("Error generating assistant response: " + e.getMessage(), e);
    }
  }
}
